### ISSUE TITLE
Difficulty understanding AccelSim-Ramulator interactions.

### ISSUE THREAD

**Issue by sbird-kick** [yongwonshin/PIMFlow#1]
Hi,

I am having some difficulty understanding how different components fit together (AccelSim, Ramulator). In particular, about Ramulator is handing GPU traces. 

Let's consider an example in which the split ratio is 50-50 (i.e. half the data is processed on the GPU cores and half in memory). I understand that AccelSim generates GPU traces i.e. when and what operation is performed on memory. Is this for 50% of the data, ignoring the other half?

The other half is fed to Ramulator. I can see that Ramulator is equipped to handle PIM memory commands such as GWrite etc. What GPU commands has the DRAM controller been modified to accept? How/when are these GPU memory commands generated (and is there a file I can easily click on and see them)?

Lastly, how are AccelSim and Ramulator running in parallel? I can imagine Ramulator is not capable of modelling computational overhead, just the time for various memory operations. AccelSim may be able to handle compute overhead but can not handle the memory overhead caused by PIM memory commands(??). How is a system that has both PIM and GPU commands simulated?

I will appreciate some clarity on these higher level flows.

**Comment by yongwonshin** [comment]
Hi,

Firstly, the open version of Ramulator is not integrated into Accel-Sim. When we replaced the Accel-Sim memory controller with Ramulator, the runtime showed quite different trends for GPUs compared to the original Accel-Sim. To avoid discrepancies between runtimes, we should tune parameters in Ramulator. So, the open version of Ramulator accepts only PIM commands, and Accel-Sim accepts only regular memory commands to match performance with the original one.

We assumed the underlying architecture strictly split the memory controller (channel) for GPU and PIM. The only interaction between the GPU and PIM memory channels is to send input data from GPU channels to PIM channels. When we used the integrated simulator (Accel-Sim + Ramulator), the runtime overhead is less than 0.3% (Refer to "Contention at memory controller" paragraph in Section 7 of our paper). More complex use cases entail interleaved handling of GPU and PIM traces at fine-grained (e.g., command) level, but this would require a more complex system architecture than ours.

Next, we generate a PIM trace at the compile time using the [TVM BYOC](https://tvm.apache.org/2020/07/15/how-to-bring-your-own-codegen-to-tvm) interface by inspecting input tensor and weight shapes. We annotate node information, which node is for GPU or PIM, at the ONNX graph level and propagate the information in Relay IR down to the BYOC interface. We catch and annotate parallel execution information at the ONNX graph level, too. So, in GraphExecutor, we use this information to decide which nodes should be executed in parallel. The open version executes two traces (GPU and Ramulator) in the Accel-Sim and Ramulator respectively.

Thank you for your interest in our work.
