### ISSUE TITLE
Got an error when "Extract network traces"

### ISSUE THREAD

**Issue by qzylalala** [yongwonshin/PIMFlow#2]
Hi！
I got an error when I prepare docker environment. It seems we don't have models in PIMFLOW project.

```
tar (child): ./data/mobilenet-v2.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
```

https://github.com/yongwonshin/PIMFlow/blob/3412b53ad109c98e4b8f0d7d5e1efebf12df4adc/README.md?plain=1#L102-L112

**Comment by yongwonshin** [comment]
Hi,

I'm sorry for the inconvenience. I'd uploaded the files in GitHub as LFS files but later noticed that it could make recurrent bills, so I deleted them. Above files could also be found in [Zenodo](https://doi.org/10.5281/zenodo.7376801) as data.zip.
